// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZS5PGn6i8LSmezSVaIcWF1IfPEc9n80',
    appId: '1:223858097045:web:e293afbc52b22627d3949c',
    messagingSenderId: '223858097045',
    projectId: 'kejar-for-parents',
    authDomain: 'kejar-for-parents.firebaseapp.com',
    storageBucket: 'kejar-for-parents.appspot.com',
    measurementId: 'G-R05H3P6SNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12h4AG7ApymPz75woYYmHZv3f3_JvzoI',
    appId: '1:223858097045:android:5b4c7bc951c72f16d3949c',
    messagingSenderId: '223858097045',
    projectId: 'kejar-for-parents',
    storageBucket: 'kejar-for-parents.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WDVCzOG9OhXFBocFiEgCdWQixe-OtMo',
    appId: '1:223858097045:ios:461a8e18de9e82dfd3949c',
    messagingSenderId: '223858097045',
    projectId: 'kejar-for-parents',
    storageBucket: 'kejar-for-parents.appspot.com',
    iosClientId: '223858097045-agklpguvsoi1dadvdi0q3omt1gdd9ch5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kejarForParents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5WDVCzOG9OhXFBocFiEgCdWQixe-OtMo',
    appId: '1:223858097045:ios:461a8e18de9e82dfd3949c',
    messagingSenderId: '223858097045',
    projectId: 'kejar-for-parents',
    storageBucket: 'kejar-for-parents.appspot.com',
    iosClientId: '223858097045-agklpguvsoi1dadvdi0q3omt1gdd9ch5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kejarForParents',
  );
}
